# Generated by Django 5.2.5 on 2025-08-15 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoryPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("story_id", models.CharField(db_index=True, max_length=255)),
                (
                    "lat",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-90.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ]
                    ),
                ),
                (
                    "lon",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-180.0),
                            django.core.validators.MaxValueValidator(180.0),
                        ]
                    ),
                ),
                ("place_name", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("admin", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("provider", models.CharField(default="nominatim", max_length=50)),
                ("provider_place_id", models.CharField(blank=True, max_length=100)),
                (
                    "confidence",
                    models.FloatField(
                        default=0.7,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("exif", "EXIF GPS"),
                            ("user_form", "User Form"),
                            ("search", "Geocoding Search"),
                            ("reverse", "Reverse Geocoding"),
                        ],
                        default="user_form",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "story_place",
                "indexes": [
                    models.Index(
                        fields=["lat", "lon"], name="story_place_lat_8c7a16_idx"
                    ),
                    models.Index(
                        fields=["city", "country"], name="story_place_city_73e11a_idx"
                    ),
                    models.Index(
                        fields=["confidence"], name="story_place_confide_04c434_idx"
                    ),
                ],
                "unique_together": {("story_id",)},
            },
        ),
    ]
