# Generated by Django 5.2.5 on 2025-08-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("body", models.TextField()),
                ("image_caption", models.CharField(blank=True, max_length=500)),
                ("alt_text", models.CharField(blank=True, max_length=500)),
                ("tags", models.JSONField(default=list)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("ta", "Tamil")],
                        default="en",
                        max_length=2,
                    ),
                ),
                (
                    "target_language",
                    models.CharField(
                        choices=[("en", "English"), ("ta", "Tamil")],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("image_url", models.URLField(blank=True)),
                ("image_alt", models.CharField(blank=True, max_length=500)),
                ("img_caption", models.TextField(blank=True)),
                ("detected_objects", models.JSONField(default=list)),
                ("attributes", models.JSONField(default=list)),
                ("ocr_text", models.TextField(blank=True)),
                ("place", models.CharField(blank=True, max_length=200)),
                ("place_confidence", models.FloatField(default=0.0)),
                ("local_time", models.CharField(blank=True, max_length=100)),
                ("season", models.CharField(blank=True, max_length=100)),
                ("merged_notes_transcript", models.TextField(blank=True)),
                ("exif_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "articles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["article_id"], name="articles_article_832340_idx"
                    ),
                    models.Index(
                        fields=["language"], name="articles_languag_6c52d8_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="articles_created_82e966_idx"
                    ),
                ],
            },
        ),
    ]
