# Generated by Django 5.2.5 on 2025-08-15 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_analysis", "0002_article"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="media/")),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("exif_datetime", models.DateTimeField(blank=True, null=True)),
                ("exif_gps_lat", models.FloatField(blank=True, null=True)),
                ("exif_gps_lon", models.FloatField(blank=True, null=True)),
                ("exif_camera_model", models.CharField(blank=True, max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "media",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ImageAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("img_caption", models.TextField(blank=True)),
                ("detected_objects", models.JSONField(default=list)),
                ("attributes", models.JSONField(default=list)),
                ("ocr_text", models.TextField(blank=True)),
                ("place", models.CharField(blank=True, max_length=200)),
                ("place_confidence", models.FloatField(default=0.0)),
                ("local_time", models.CharField(blank=True, max_length=100)),
                ("season", models.CharField(blank=True, max_length=100)),
                ("user_notes", models.TextField(blank=True)),
                ("merged_notes_transcript", models.TextField(blank=True)),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                ("ai_model", models.CharField(default="gpt-4o", max_length=50)),
                (
                    "media",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="image_analysis.media",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Image analyses",
                "db_table": "image_analysis",
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        choices=[("en", "English"), ("ta", "Tamil")],
                        default="en",
                        max_length=2,
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("reportage", "Reportage"),
                            ("travelogue", "Travelogue"),
                            ("diary", "Diary"),
                        ],
                        default="diary",
                        max_length=20,
                    ),
                ),
                (
                    "length",
                    models.CharField(
                        choices=[
                            ("short", "Short"),
                            ("medium", "Medium"),
                            ("long", "Long"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("story_date", models.DateField(blank=True, null=True)),
                ("place_str", models.TextField(blank=True)),
                ("place_confidence", models.FloatField(default=0.0)),
                ("json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "share_token",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order_idx", models.PositiveIntegerField()),
                ("local_time", models.CharField(blank=True, max_length=5)),
                ("daypart", models.CharField(blank=True, max_length=16)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_items",
                        to="image_analysis.media",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="image_analysis.story",
                    ),
                ),
            ],
            options={
                "db_table": "story_items",
                "ordering": ["order_idx"],
                "unique_together": {("story", "order_idx")},
            },
        ),
    ]
